config/routes.rb
Rails.application.routes.draw do
  get 'home/main'

  get 'profile/index'  

  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'welcome/index'

  get 'display/show'

  resources :images

  root 'home#main'

end

app/models/image.rb
class Image < ActiveRecord::Base

  belongs_to :listing
  has_attached_file :pic
  validates_attachment_content_type :pic, content_type:  /\Aimage/
end

app/models/listing.rb
class Listing < ActiveRecord::Base

  has_many :images
  belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pictures
  has_one :listing
  has_attached_file :profile_pic
  validates_attachment_content_type :profile_pic, content_type:  /\Aimage/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/display_controller.rb
class DisplayController < ApplicationController

  require 'base64'

  def show
    @food = ClarifaiRuby::TagRequest.new.get(Base64.encode64(Image.find_by(params[:id]).pic.url), model: "food-items-v0.1")
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def main
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index 
     @img = Image.create(:listing_id => current_user.listing.id) 
  end

  def show
    @img = Image.find(params[:id])
  end

  def update
   @img = Image.find(params[:id])  
    respond_to do |f|
      if @img.update(img_params)
        f.html{ redirect_to @img, notice: 'Photo was successfully uploaded'}
        f.json{ render :show, status: :ok, location: @img }
      else
        f.html { render :edit }
        f.json { render json: @img.errors, status: :unprocessable_entity }
      end
    end
  end

  private
 
    def img_params
      params.require(:image).permit(:pic)
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  before_action :create_listing, :check_empty_images

  def index
    @user = current_user
  end

  def create_listing
    if !current_user.listing
      Listing.create(:user_id => current_user.id).save
    end
  end

  def check_empty_images
    current_user.listing.images.each do |i|
      if !i.pic_file_name
        i.destroy
      end
    end
  end



end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :profile_pic, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @something = ClarifaiRuby::TagRequest.new.get("http://res.cloudinary.com/dzmp7xptn/image/upload/v1471102345/taco_lww6md.jpg", model: "food-items-v0.1")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/display_helper.rb
module DisplayHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/display/show.html.erb
<% max = 0 %>
<% word = "" %>
<% @food.tag_images.each do |c| %>
  <% c.instance_values["tags"].each do |f| %>
    <% if f.prob > max%>
      <% max = f.prob %>
      <% word = f.word%>
    <% else %>
      <% next %>
    <% end %>
  <% end %>
<% end %>  

<h1> It's  <%= word %> !!!</h1>
<h2>We are <%= (max*100).to_s[0..4]%>% sure :)</h2>

<h2>Places you can find it</h2>
<% params = { term: word.to_s }

locale = { lang: 'en' } %>
<% Yelp.client.search('New York',params, locale).instance_values["businesses"].each do |f| %>
<h4><%=  f.name %></h4>
<h5><%= f.location.address[0] %>, <%= f.location.city %>, <%= f.location.postal_code %></h5>
<% end %>

<%= link_to "Back to profile", profile_index_path %>

app/views/home/main.html.erb
<br><br><br><br>
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-5">
			<h1 style="font-size:80px;"><strong>FeedMeWhatever</strong></h1>

		</div>
	
				</div>
				

		</div>


</div>

<br><br>

<section id="photos" style="height: 318px">
						<%= image_tag("foodporn.jpg")%>
						<%= image_tag("foodporn2.jpg")%>
						<%= image_tag("foodporn3.jpg")%>
						<%= image_tag("foodporn4.jpg")%>
						<%= image_tag("foodporn4.jpg")%>
	
</section>
<br><br>
<section id="how">
	<h2 class="text-center">How it works</h2>
	<p>Hexagon mixtape knausgaard slow-carb squid. Tilde hella pok pok, umami DIY live-edge 8-bit. Fixie pinterest listicle mumblecore vice, chillwave cred next level portland twee trust fund scenester. Gastropub viral enamel pin, man braid chicharrones activated charcoal whatever listicle. Selfies single-origin coffee flexitarian irony. XOXO pok pok hammock, tbh poutine kombucha freegan vegan crucifix live-edge scenester blue bottle woke cold-pressed. Taxidermy aesthetic YOLO, edison bulb polaroid slow-carb quinoa messenger bag franzen.</p>
</section>

app/views/images/index.html.erb
<%= form_for @img, html: { multipart: true } do |form| %>
  <%= form.file_field :pic %>
  <%= form.submit "Upload"%>
<% end %>

app/views/images/show.html.erb
<%= image_tag @img.pic.url %>
<%= link_to "Back to profile", profile_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<!--Google Fonts-->
<link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" style="background-color: #fff;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <strong><%= link_to "FeedMeWhatever", home_main_path, :class => "nav navbar-brand" %></strong>
    </div>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in?  %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_user.first_name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", profile_index_path %></li>
            <li><%= link_to "Edit", edit_user_registration_path %></li>

          </ul>
        </li>


<li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
<% else %>
<li><%= link_to "Sign Up", new_user_registration_path %></li>
<li> <%= link_to "Log In", new_user_session_path %></li>
<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= yield %>
<!--Bootstrap JS-->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/welcome/index.html.erb
<% max = 0 %>
<% word = "" %>
<% @something.tag_images.each do |c| %>
  <% c.instance_values["tags"].each do |f| %>
    <% if f.prob > max%>
      <% max = f.prob %>
      <% word = f.word%>
    <% else %>
      <% next %>
    <% end %>
  <% end %>
<% end %>  
<h1>HERE IS THE BEST WORD</h1>
<h2> <%= word %> with a probability of <%= max%> </h2>

<h2>Yelp Shit</h2>
<% params = { term: '#{@word}',
           limit: 3
         }

locale = { lang: 'en' } %>
<% Yelp.client.search('New York').instance_values["businesses"].each do |f| %>
<h4><%=  f.name %></h4>
<% end %>